"""empty message

Revision ID: 2174d69a6665
Revises: 7f9d10a75dd1
Create Date: 2019-03-13 23:07:10.160660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2174d69a6665'
down_revision = '7f9d10a75dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('joined', sa.String(length=50), nullable=True))
    op.drop_column('user_profiles', 'joined_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('joined_on', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'joined')
    # ### end Alembic commands ###
