"""empty message

Revision ID: 8c419c6f2cdf
Revises: 2174d69a6665
Create Date: 2019-03-14 03:09:37.520986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c419c6f2cdf'
down_revision = '2174d69a6665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('biograph', sa.VARCHAR(), nullable=True))
    op.drop_column('user_profiles', 'biography')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('biography', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'biograph')
    # ### end Alembic commands ###
